### ISSUE TITLE
"Last edited" column on groups page doesn't render correctly after group is updated

### ISSUE THREAD

**Issue by clevinson** [regen-network/groups-ui#94]
When a group is updated via the user interface, the `updatedAt` field in the metadata is set as a unix timestamp.

Group #26 (RUUTS - Testing Group) was updated via the UI to have a new group name, and as a result the group metadata was set to:
```json
{"name":"RUUTS - Testing Group","updatedAt":"1686608124339"}
```

This results in an incorrect rendering of the "Last Edited" column on the groups UI page (see screenshot below).

However, another group "Cory Group (testing 2)" (group #13) rendered the "Last Edited" column correctly. This group has not had updates made via the UI, and when querying its metadata on-chain, one can see it stores the date as a formatted string:

```json
{"name":"Cory Group (testing 2)","description":"","forumLink":"","updatedAt":"Thu Apr 20 2023 18:44:43 GMT-0700 (Pacific Daylight Time)","other":""}
```

We should pick one serialization format (string or unix timestamp) and ensure that whenever we write metadata we use it consistently.

See screenshot of bug below:
<img width="1284" alt="Screenshot 2023-06-12 at 5 00 46 PM" src="https://github.com/regen-network/groups-ui/assets/832188/e7aa2468-f656-4290-8790-7f1e4ab98202">

**Comment by ryanchristo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RND-Dev-Team-5f8998bec8958d000f4609e2/issues/regen-network/groups-ui/94?planning-poker) with Zenhub @blushi @wgwz

**Comment by ryanchristo** [comment]
Per discussion with Erka, it probably makes the most sense to just remove it from the metadata.

**Comment by blushi** [comment]
Yeah as discussed, this "last edited" value will be wrong anyway in case of updates made through a proposal (when the policy is the admin) since we cannot know in advance when/if the proposal will be executed successfully and the updates applied. This could be wrong as well in case of updates happening outside the app. In order to have it right, we would need to store the "last edited" value elsewhere than in the metadata (indexed off-chain?) and this goes a bit beyond the scope of the MVP.

**Comment by blushi** [comment]
converting this to a 1 since it's just about removing updatedAt from group metadata
